### ISSUE TITLE
check-satisfied error when arguments swapped links to location within rackunit

### ISSUE THREAD

**Issue by dbp** [logiccomp/lsl#10]
Here's a reproduction:

```
#lang lsl

(define (f x) #t)

(check-satisfied f #t)
 ```

The error message is... reasonable (seems like it could, in theory, be better, but it's not too bad), but the srcloc (the red X that is linked) is messed up for some reason....

**Comment by camoy** [comment]
Looks like this now:

![2023-12-23_17-12](https://github.com/logiccomp/lsl/assets/556446/78a64f69-f1de-47a9-a8ea-4244be0a2a67)

The error was directly inherited from `rackunit` which didn't do any input validation of its own. I've added to some of the other `check` forms some contracts as well.
