### ISSUE TITLE
Fall-through predicate case for define-contract doesn't work for contracts with parameters

### ISSUE THREAD

**Issue by dbp** [logiccomp/lsl#16]
`(define Foo (lambda (x) ...)` works, but `(define (Foo x) (lambda (y) ...))` errors with `literal clause must occur within Flat`; obviously wrapping the `lambda` with `Flat` works, but would be nice to have the shorthand.

**Comment by camoy** [comment]
Do you have a more complete example of this behavior? This works for me:
```rkt
(define-contract (Equal x) (lambda (y) (= x y)))

(: f (-> (Equal 1) (Equal 1)))
(define (f x) x)

(f 1)
```

**Comment by dbp** [comment]
Oh, it was my mistake; I had `(check (lambda ...))`. Sorry!
