### ISSUE TITLE
Be able to change how many tests `check-contract` runs

### ISSUE THREAD

**Issue by dbp** [logiccomp/lsl#18]
Simplest might be an extra argument? i.e., `(check-contract foo)` does default, `(check-contract N foo)` generates `N` sets of inputs?

**Comment by camoy** [comment]
Already implemented as `(check-contract foo N)` :)

It does not print these out as separate tests, though. Each `check-contract` is considered one test when printing out the summary.

**Comment by dbp** [comment]
Ahh, wonderful :)
