### ISSUE TITLE
Allow structs to be mutable

### ISSUE THREAD

**Issue by dbp** [logiccomp/lsl#21]
I _thought_ this was just a matter of adding #:mutable, but this is causing a test failure (good!), so obviously there is something going on. I get why this could cause problems (mutability certainly changes how equality can work!), but not sure how to _fix_ it :)

**Comment by camoy** [comment]
There's any easy fix for this (which I've pushed). But there's a bigger question about the meaning of struct contracts when they're mutable. At the moment I've assumed structs are immutable and are flat. However, once they're mutable then they become higher-order and need to be impersonated/chaperoned like procedures are to enforce the contract when a client calls `set-struct-field!`.

**Comment by camoy** [comment]
Turns out that the traditional implementation strategy of using impersonators for structs doesn't work because of Rosette. Instead I'm simulating the same kind of behavior with a special kind of proxy struct that respects equality and contains contracts for fields. Somewhat messy, but should work.
