### ISSUE TITLE
Improve error messages for existentials

### ISSUE THREAD

**Issue by dbp** [logiccomp/lsl#25]
The example given in the test suite mentions that it gets a sealed value, but doesn't mention the existential at all, which I imagine will be confusing. Can we store some metadata with the sealed value so when we print the error we can say a little bit about it (ideally highlighting where it was sealed). 

More confusingly, if you generate two copies of the same existential (which I'm sure people will do!), and try to use one with the other, it goes wrong (good!) but I imagine the error will be quite hard to reason through. 

e.g., like this:

```

(: mk-counter-pkg (-> (Exists (A) (Tuple (-> A) (-> A A) (-> A Integer)))))
(define (mk-counter-pkg)
  (list (λ () 0)
        (λ (x) (+ x 1))
        (λ (x) x)))

(define COUNTER0 (mk-counter-pkg))
(define COUNTER1 (mk-counter-pkg))
(define make-counter (first COUNTER0))
(define counter-incr (second COUNTER1))

(counter-incr (make-counter))
```

This produces, as an error:

```
. . mk-counter-pkg: contract violation
  expected: A
  given: #<seal>
  blaming: anonymous-module (as client)
```

(and highlights the A argument to the second field of the Tuple -- i.e., the argument to the counter-incr)

**Comment by camoy** [comment]
Here's the new error message. I've distinguished between existentials and universals, but also subscripted the names so that you can see these are different instantiations of the same existential.

```
mk-counter-pkg: contract violation
  expected: ∃A₁
  given: ∃A₀
  blaming: anonymous-module (as client)
```
