### ISSUE TITLE
"size" argument for generators, shrinking?

### ISSUE THREAD

**Issue by dbp** [logiccomp/lsl#5]
I'm wondering if we want to have the ability to have `check-contract` go from small values to larger values, rather than using the _same_ function to generate values. 

Similarly, should we have a way to shrink values? Optional, defaulting to being absent?

**Comment by camoy** [comment]
Implemented now:

* Generators take a `fuel` argument that (roughly) should control the size.
* Shrinking.
* `check-contract` will attempt to shrink as much as possible before raising an error.

**Comment by dbp** [comment]
💯
