### ISSUE TITLE
Recursive contract expanding infinitely?

### ISSUE THREAD

**Issue by dbp** [logiccomp/lsl#7]
Just defining this:
```
(define-contract SExp (OneOf Symbol
                             Integer
                             Boolean
                             (List SExp)))
```
Works fine (using, as I understand, the stuff you did to autodetect the recursive binding).

But trying to _use_ it:
```
(: f (-> SExp True))
(define (f s) #t)
```

Seems to infinite loop (or at least, OOMs..)

**Comment by camoy** [comment]
I think this is because `List` is not defined as `(OneOf Nil (Cons X (List X))`, but rather as a flat contract. For this to work, we might have to define our own lists and replace Racket's built-in ones.

**Comment by dbp** [comment]
This seems relatively important, as I think Lists will end up being used like this in various places (n-ary trees for example).  Not worth special casing the contract for list to not be Flat, is it?

**Comment by camoy** [comment]
That's another possibility. I can try that solution first and see if it's easier.
