### ISSUE TITLE
Parametric signatures?

### ISSUE THREAD

**Issue by dbp** [logiccomp/lsl#9]
We have parametric contracts, though they have to be made concrete on _use_. Is it feasible to add contract variables? i.e., I can write:

```
(define-contract (Maybe T) (OneOf T (Constant #f))))
```

Which is great, but I can't (as far as I know!), write:

```
(: map (-> (-> X Y) (List X) (List Y)))
...
```

**Comment by camoy** [comment]
It's not supported at the moment, but we can do this. One possible interpretation of the contract variables is just to replace them with `Any`. That's easy, but not enforcing anything like parametricity. The "correct" way to do it is to perform sealing at negative positions and unsealing at positive positions (as in [Arjun's paper](https://cs.brown.edu/people/aguha/papers/guha-dls2007.pdf)). Of course, this means violations of parametricity yield a weird run-time error (e.g. `expected: integer? got: #<seal>`). Thoughts on what makes more sense for us?

**Comment by dbp** [comment]
I think doing sealing makes sense. As long as the blame is decent, the error will make enough sense (once explained) and the alternative is pretty crappy (it’s how Sperbers checked signatures worked, and I didn’t like it in fundies 1, so really don’t think it’ll be great for Logic…)

**Comment by camoy** [comment]
If we're doing parametric contracts, then it's trivial to add in [existential contracts](https://docs.racket-lang.org/guide/contracts-exists.html) as well. You could then do parametricity, data abstraction, capabilities, and other related topics in class perhaps.

**Comment by dbp** [comment]
All those things would be _wonderful_ to be able to cover.
